site_name:  Documentation
site_description: CMU -  Documentation
site_author: CMU  Group
site_url: https://.docs.cern.ch/

repo_name: GitLab
repo_url: https://gitlab.cern.ch/cms-cmu/
edit_uri: 'blob/master/docs'

theme:
  name: material
  font: false
  logo: assets/CMU-logo.png
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/fonts.css
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - abbr
  - pymdownx.snippets
  - admonition
  - def_list
  - footnotes
  - tables
  - meta
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.snippets:
      check_paths : true
      restrict_base_path: false

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_parallel_processing: false
  - mkdocs-video
  - privacy
  - termynal


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/feedback.js


nav:
    - Home: index.md
    - Source Code:
        - index: src/index.md
        - tools: src/tools.md
    - Software:
        - index: software/index.md
    - Classifier:
        - uackend: classifier/backend.md
        - hcr: classifier/hcr.md
        - index: classifier/index.md
        - monitor: classifier/monitor.md
        - task: classifier/task.md
    - HH4b Analysis:
        - analysis-tests: bbbb/analysis-tests.md
        - analysis-tools-hists: bbbb/analysis-tools-hists.md
        - analysis-tools-ikappa: bbbb/analysis-tools-ikappa.md
        - analysis-tools: bbbb/analysis-tools.md
        - analysis-weights-pytorch models: bbbb/analysis-weights-pytorch_models.md
        - analysis: bbbb/analysis.md
        - index: bbbb/index.md
        - jet clustering: bbbb/jet_clustering.md
        - metadata: bbbb/metadata.md
        - plots: bbbb/plots.md
        - reana suumission: bbbb/reana_submission.md
        - skimmer: bbbb/skimmer.md
        - stats analysis: bbbb/stats_analysis.md
        - workflows: bbbb/workflows.md
    - bbWW Analysis:
        - index: bbWW/index.md
    - Cupping Notes:
        - 20260917 nominal run2 5978ff3-0ecb080: prod/20260917_nominal_run2_5978ff3-0ecb080.md
        - 20260917 smoke 00276d9-5730uda: prod/20260917_smoke_00276d9-5730bda.md
        - index: prod/index.md
    - Documentation: readme.md
