apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-cmu-storage
  namespace: cms-cmu
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-cephfs
